### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by 10xjs** [10xjs/form#26]
- [ ] Migrate to typescript
- [ ] Implement state management using react hooks
- [ ] Optimize rollup build
- [ ] UMD build
- [ ] export `useForm`, `useField` and `useFieldArray` hooks
- [ ] stricter types
